// Generated by https://quicktype.io

export interface OptimusSchema {
  definitions: Definitions;
  $schema: string;
  $id: string;
  type: string;
  title: string;
  required: string[];
  properties: Properties;
}

export interface Definitions {
}

export interface Properties {
  enabled: Property;
  name: Property;
  sample: Property;
  transformer: Property;
  function: Property;
}

export interface Property {
  $id: string;ß
  type: string;
  title: string;
  default: string;
  examples: string[];
}
