// Generated by https://quicktype.io

export interface OptimusSchema {
  definitions: Definitions;
  $schema: string;
  $id: string;
  type: string;
  title: string;
  required: string[];
  properties: Properties;
}

export interface Definitions {
}

export interface Properties {
  enabled: Enabled;
  name: Function;
  sample: Function;
  transformer: Function;
  function: Function;
}

export interface Enabled {
  $id: string;
  type: string;
  title: string;
  default: boolean;
  examples: boolean[];
}

export interface Function {
  $id: string;
  type: string;
  title: string;
  default: string;
  examples: string[];
  pattern: string;
}
